
dataset:
	wget http://benchmark.ini.rub.de/Dataset/GTSRB_Final_Training_Images.zip
	unzip GTSRB_Final_Training_Images.zip -d training
	mv training/GTSRB/Final_Training/Images/* training/
	rm -rf training/GTSRB/
	wget http://benchmark.ini.rub.de/Dataset/GTSRB_Final_Test_Images.zip
	unzip GTSRB_Final_Test_Images.zip -d test
	mv test/GTSRB/Final_Test/Images/* test/
	rm -rf test/GTSRB/
